#!/usr/bin/env bash
# This script displays To infinity and beyond and displays I am invinvible when receiving a SIGTERM signal

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
