#!/usr/bin/env bash
# This script displays the content of the /etc/passwd file using while and IFS

while IFS=: read -r user pass uid gid full home shell
do
	echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $full"
done < /etc/passwd
