#!/usr/bin/env bash
# This script is used to print Best school using while loop 10 times

count=1
while [ $count -le 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((count ++))
done
